### ISSUE TITLE
last details

### ISSUE THREAD

**Issue by guer0125** [guer0125/accessibility-fixer-upper#1]
Hi, for this one marbot is asking

1. `div` tags within "prodeucts" list, after `img` should have IDs that `aira-details` can point to... **i already did this, not sure what im doing wrong**

2. it's asking to have :focus in **css** i tried a:focus and nav a:focus and it's still giving me an error

@muxlowc

**Comment by muxlowc** [comment]
@guer0125 I actually noticed a typo in what Markbot is looking for, so I dont think you'll get it to pass :( Sorry about that!

Add in this:
.nav a:hover,
.nav a:focus {
  background-color: #fff;
  color: #113c00;
}

And i'll go ahead and give you the mark manually!

**Comment by guer0125** [comment]
done :)
